### PR TITLE
fixes #26; maintains backwards compatibility

### LINKED ISSUE #26: Gem does not build on Ruby 3.0
Hi there. It looks like ruby-shadow has issues building with Ruby 3.0 now:

```
[31mGem::Ext::BuildError: ERROR: Failed to build gem native extension.

[0m

    current directory: /workdir/vendor/bundle/ruby/3.0.0/gems/ruby-shadow-2.5.0

/usr/local/bin/ruby -I /usr/local/lib/ruby/3.0.0 -r

./siteconf20201228-24-y27djp.rb extconf.rb

checking for getspent() in -lshadow... no

checking for getspent()... yes

checking for fgetspent()... yes

checking for setspent()... yes

checking for endspent()... yes

checking for lckpwdf()... yes

checking for ulckpwdf()... yes

checking for sgetspent()... yes

checking for ruby/io.h... yes

creating Makefile



current directory: /workdir/vendor/bundle/ruby/3.0.0/gems/ruby-shadow-2.5.0

make "DESTDIR=" clean



current directory: /workdir/vendor/bundle/ruby/3.0.0/gems/ruby-shadow-2.5.0

make "DESTDIR="

compiling shadow/shadow.c

shadow/shadow.c: In function 'rb_shadow_fgetspent':

shadow/shadow.c:21:26: error: 'struct rb_io_t' has no member named 'f'; did you

mean 'fd'?

   21 | #define file_ptr(x) (x)->f

      |                          ^

shadow/shadow.c:95:22: note: in expansion of macro 'file_ptr'

   95 |   entry = fgetspent( file_ptr( (RFILE(file)->fptr) ) );

      |                      ^~~~~~~~

shadow/shadow.c: In function 'rb_shadow_putspent':

shadow/shadow.c:21:26: error: 'struct rb_io_t' has no member named 'f'; did you

mean 'fd'?

   21 | #define file_ptr(x) (x)->f

      |                          ^

shadow/shadow.c:154:11: note: in expansion of macro 'file_ptr'

  154 |   cfile = file_ptr( RFILE(file)->fptr );

      |           ^~~~~~~~

make: *** [Makefile:245: shadow.o] Error 1



make failed, exit code 2



Gem files will remain installed in

/workdir/vendor/bundle/ruby/3.0.0/gems/ruby-shadow-2.5.0 for inspection.

Results logged to

/workdir/vendor/bundle/ruby/3.0.0/extensions/x86_64-linux/3.0.0/ruby-shadow-2.5.0/gem_make.out



[0m[31mAn error occurred while installing ruby-shadow (2.5.0), and Bundler

cannot continue.

Make sure that `gem install ruby-shadow -v '2.5.0' --source

'https://rubygems.org/'` succeeds before bundling.[0m
```

### PR DESCRIPTION
**Pull request by cgoettel**

### CODE REVIEW

**Comment by cgoettel** [comment]
If merged, we'll need a new tag and then push that to the gem repository

**Comment by apalmblad** [comment]
Thanks for reaching out; saw the old PR and never got to it - the reminder was useful.  I'll to push a new release as soon as I track down my rubygems creds.  

Deja vu, I somehow ended up as the maintainer of this back in the ol' ruby 1.9 days - wanting to use chef and ruby1.9.  Nice to see the ruby 3 changes are more of an issue with compiler configuration than anything really hard.

**Comment by cgoettel** [comment]
Thanks!

From what I can see, Ruby 3 is backwards compatible with Ruby 2, but I'm not seeing anything about Ruby 1.9. I'm going to keep doing some digging and I'll open an issue if I find anything.
