### ISSUE TITLE
Gem does not build on Ruby 3.0

### ISSUE THREAD

**Issue by tas50** [apalmblad/ruby-shadow#26]
Hi there. It looks like ruby-shadow has issues building with Ruby 3.0 now:

```
[31mGem::Ext::BuildError: ERROR: Failed to build gem native extension.

[0m

    current directory: /workdir/vendor/bundle/ruby/3.0.0/gems/ruby-shadow-2.5.0

/usr/local/bin/ruby -I /usr/local/lib/ruby/3.0.0 -r

./siteconf20201228-24-y27djp.rb extconf.rb

checking for getspent() in -lshadow... no

checking for getspent()... yes

checking for fgetspent()... yes

checking for setspent()... yes

checking for endspent()... yes

checking for lckpwdf()... yes

checking for ulckpwdf()... yes

checking for sgetspent()... yes

checking for ruby/io.h... yes

creating Makefile



current directory: /workdir/vendor/bundle/ruby/3.0.0/gems/ruby-shadow-2.5.0

make "DESTDIR=" clean



current directory: /workdir/vendor/bundle/ruby/3.0.0/gems/ruby-shadow-2.5.0

make "DESTDIR="

compiling shadow/shadow.c

shadow/shadow.c: In function 'rb_shadow_fgetspent':

shadow/shadow.c:21:26: error: 'struct rb_io_t' has no member named 'f'; did you

mean 'fd'?

   21 | #define file_ptr(x) (x)->f

      |                          ^

shadow/shadow.c:95:22: note: in expansion of macro 'file_ptr'

   95 |   entry = fgetspent( file_ptr( (RFILE(file)->fptr) ) );

      |                      ^~~~~~~~

shadow/shadow.c: In function 'rb_shadow_putspent':

shadow/shadow.c:21:26: error: 'struct rb_io_t' has no member named 'f'; did you

mean 'fd'?

   21 | #define file_ptr(x) (x)->f

      |                          ^

shadow/shadow.c:154:11: note: in expansion of macro 'file_ptr'

  154 |   cfile = file_ptr( RFILE(file)->fptr );

      |           ^~~~~~~~

make: *** [Makefile:245: shadow.o] Error 1



make failed, exit code 2



Gem files will remain installed in

/workdir/vendor/bundle/ruby/3.0.0/gems/ruby-shadow-2.5.0 for inspection.

Results logged to

/workdir/vendor/bundle/ruby/3.0.0/extensions/x86_64-linux/3.0.0/ruby-shadow-2.5.0/gem_make.out



[0m[31mAn error occurred while installing ruby-shadow (2.5.0), and Bundler

cannot continue.

Make sure that `gem install ruby-shadow -v '2.5.0' --source

'https://rubygems.org/'` succeeds before bundling.[0m
```

**Comment by anatol** [comment]
Here is a proposed fix https://github.com/chef/ruby-shadow/commit/ef2432e8ddff89292649979467685b3fc86d6a5e

**Comment by cgoettel** [comment]
Is there any effort being done to merge that fix into this codebase? There hasn't been a new release of ruby-shadow for six years, but Chef is still using it (and it doesn't work on Ruby 3.0.0).

@apalmblad are you willing to continue maintaining this? I can help or fork and maintain it myself (or maybe get Chef to maintain it).

**Comment by yangkkokk** [comment]
og data follows:
| DEBUG: Executing python function extend_recipe_sysroot
| NOTE: Direct dependencies are ['/home/ko/nilrt/sources/openembedded-core/meta/recipes-core/glibc/glibc_2.33.bb:do_populate_sysroot', '/home/ko/nilrt/sources/openembedded-core/meta/recipes-devtools/gcc/gcc-runtime_10.3.bb:do_populate_sysroot', '/home/ko/nilrt/sources/openembedded-core/meta/recipes-devtools/ruby/ruby_3.0.3.bb:do_populate_sysroot', '/home/ko/nilrt/sources/openembedded-core/meta/recipes-devtools/quilt/quilt-native_0.66.bb:do_populate_sysroot', 'virtual:native:/home/ko/nilrt/sources/openembedded-core/meta/recipes-devtools/pseudo/pseudo_git.bb:do_populate_sysroot', '/home/ko/nilrt/sources/openembedded-core/meta/recipes-devtools/gcc/gcc-cross_10.3.bb:do_populate_sysroot', 'virtual:native:/home/ko/nilrt/sources/openembedded-core/meta/recipes-devtools/patch/patch_2.7.6.bb:do_populate_sysroot', 'virtual:native:/home/ko/nilrt/sources/openembedded-core/meta/recipes-devtools/ruby/ruby_3.0.3.bb:do_populate_sysroot']
| NOTE: Installed into sysroot: []
| NOTE: Skipping as already exists in sysroot: ['glibc', 'gcc-runtime', 'ruby', 'quilt-native', 'pseudo-native', 'gcc-cross-x86_64', 'patch-native', 'ruby-native', 'linux-libc-headers', 'libgcc', 'libyaml', 'zlib', 'libffi', 'readline', 'gdbm', 'openssl', 'automake-native', 'binutils-cross-x86_64', 'zlib-native', 'texinfo-dummy-native', 'libmpc-native', 'mpfr-native', 'gnu-config-native', 'libtool-native', 'xz-native', 'autoconf-native', 'flex-native', 'gmp-native', 'attr-native', 'openssl-native', 'libyaml-native', 'readline-native', 'opkg-utils', 'ncurses', 'gettext-minimal-native', 'm4-native', 'ncurses-native', 'pkgconfig-native']
| DEBUG: Python function extend_recipe_sysroot finished
| DEBUG: Executing shell function do_install
| Building native extensions. This could take a while...
| ERROR:  Error installing ruby-shadow-2.5.0.gem:
|       ERROR: Failed to build gem native extension.
|
|     current directory: /home/ko/nilrt/build/tmp-glibc/work/core2-64-nilrt-linux/ruby-shadow/2.5.0-r0/image/usr/lib/ruby/gems/3.0.0/gems/ruby-shadow-2.5.0
| /home/ko/nilrt/build/tmp-glibc/work/core2-64-nilrt-linux/ruby-shadow/2.5.0-r0/recipe-sysroot-native/usr/bin/ruby -I /home/ko/nilrt/build/tmp-glibc/work/core2-64-nilrt-linux/ruby-shadow/2.5.0-r0/recipe-sysroot-native/usr/lib/ruby/3.0.0 -r ./siteconf20240622-4741-7r6um9.rb extconf.rb
| checking for getspent() in -lshadow... no
| checking for getspent()... yes
| checking for fgetspent()... yes
| checking for setspent()... yes
| checking for endspent()... yes
| checking for lckpwdf()... yes
| checking for ulckpwdf()... yes
| checking for sgetspent()... yes
| checking for ruby/io.h... yes
| creating Makefile
| creating Makefile
|
| current directory: /home/ko/nilrt/build/tmp-glibc/work/core2-64-nilrt-linux/ruby-shadow/2.5.0-r0/image/usr/lib/ruby/gems/3.0.0/gems/ruby-shadow-2.5.0
| make DESTDIR\= clean
|
| current directory: /home/ko/nilrt/build/tmp-glibc/work/core2-64-nilrt-linux/ruby-shadow/2.5.0-r0/image/usr/lib/ruby/gems/3.0.0/gems/ruby-shadow-2.5.0
| make DESTDIR\=
| compiling shadow/shadow.c
| shadow/shadow.c: In function 'rb_shadow_fgetspent':
| shadow/shadow.c:21:26: error: 'struct rb_io_t' has no member named 'f'; did you mean 'fd'?
|    21 | #define file_ptr(x) (x)->f
|       |                          ^
| shadow/shadow.c:95:22: note: in expansion of macro 'file_ptr'
|    95 |   entry = fgetspent( file_ptr( (RFILE(file)->fptr) ) );
|       |                      ^~~~~~~~
| shadow/shadow.c: In function 'rb_shadow_putspent':
| shadow/shadow.c:21:26: error: 'struct rb_io_t' has no member named 'f'; did you mean 'fd'?
|    21 | #define file_ptr(x) (x)->f
|       |                          ^
| shadow/shadow.c:154:11: note: in expansion of macro 'file_ptr'
|   154 |   cfile = file_ptr( RFILE(file)->fptr );
|       |           ^~~~~~~~
| make: *** [Makefile:245: shadow.o] Error 1
|
| make failed, exit code 2
|
| Gem files will remain installed in /home/ko/nilrt/build/tmp-glibc/work/core2-64-nilrt-linux/ruby-shadow/2.5.0-r0/image/usr/lib/ruby/gems/3.0.0/gems/ruby-shadow-2.5.0 for inspection.
| Results logged to /home/ko/nilrt/build/tmp-glibc/work/core2-64-nilrt-linux/ruby-shadow/2.5.0-r0/image/usr/lib/ruby/gems/3.0.0/extensions/x86_64-linux/3.0.0/ruby-shadow-2.5.0/gem_make.out
| WARNING: exit code 1 from a shell command.
| ERROR: ExecutionError('/home/ko/nilrt/build/tmp-glibc/work/core2-64-nilrt-linux/ruby-shadow/2.5.0-r0/temp/run.do_install.4393', 1, None, None)

not work #27
