### ISSUE TITLE
ruby-shadow does not build on Ruby 2.0.0-p0

### ISSUE THREAD

**Issue by jtimberman** [apalmblad/ruby-shadow#11]
The C extension fails to build on Ruby 2.0.0-p0.

```
% ruby extconf.rb
checking for getspent() in -lshadow... no
checking for getspent()... yes
checking for fgetspent()... yes
checking for setspent()... yes
checking for endspent()... yes
checking for lckpwdf()... yes
checking for ulckpwdf()... yes
checking for sgetspent()... yes
creating Makefile

% make
compiling shadow.c
In file included from shadow.c:16:0:
/home/jtimberman/.rvm/rubies/ruby-2.0.0-p0/include/ruby-2.0.0/ruby/backward/rubyio.h:2:2: warning: #warning use "ruby/io.h" instead of "rubyio.h" [-Wcpp]
shadow.c: In function ‘rb_shadow_fgetspent’:
shadow.c:89:22: error: ‘struct rb_io_t’ has no member named ‘f’
shadow.c: In function ‘rb_shadow_putspent’:
shadow.c:173:11: error: ‘struct rb_io_t’ has no member named ‘f’
make: *** [shadow.o] Error 1
```

This appears to be due to RUBY_VERSION not matching the regexp in extconf.rb. This seems to work:

``` ruby
CFLAGS = case RUBY_VERSION
          when /1\.9/; '-DRUBY19'
          when /2\.0/; '-DRUBY19'
          else; ''
          end
```

But I'm not sure if this is the most idiomatic way to do this.
